name: github pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mashhad-app
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Install NodeJS
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      # Publish the site
      - name: Publish
        run: |
          npm install
          npm run build

      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: mashhad-app/dist
          force_orphan: true
